//
// AnalyticsRuleType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AnalyticsRuleType: String, Codable, CaseIterable {
    case popularQueries = "popular_queries"
    case nohitsQueries = "nohits_queries"
    case counter = "counter"
    case log = "log"
}
