//
// AnalyticsEventsResponseEventsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsEventsResponseEventsInner: Codable {

    public var collection: String?
    public var docId: String?
    public var docIds: [String]?
    public var eventType: String?
    public var name: String?
    public var query: String?
    public var timestamp: Int64?
    public var userId: String?

    public init(collection: String? = nil, docId: String? = nil, docIds: [String]? = nil, eventType: String? = nil, name: String? = nil, query: String? = nil, timestamp: Int64? = nil, userId: String? = nil) {
        self.collection = collection
        self.docId = docId
        self.docIds = docIds
        self.eventType = eventType
        self.name = name
        self.query = query
        self.timestamp = timestamp
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collection
        case docId = "doc_id"
        case docIds = "doc_ids"
        case eventType = "event_type"
        case name
        case query
        case timestamp
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collection, forKey: .collection)
        try container.encodeIfPresent(docId, forKey: .docId)
        try container.encodeIfPresent(docIds, forKey: .docIds)
        try container.encodeIfPresent(eventType, forKey: .eventType)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(query, forKey: .query)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}
