//
// AnalyticsRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsRule: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case popularQueries = "popular_queries"
        case nohitsQueries = "nohits_queries"
        case counter = "counter"
        case log = "log"
    }
    public var name: String
    public var type: ModelType
    public var collection: String
    public var eventType: String
    public var ruleTag: String?
    public var params: AnalyticsRuleCreateParams?

    public init(name: String, type: ModelType, collection: String, eventType: String, ruleTag: String? = nil, params: AnalyticsRuleCreateParams? = nil) {
        self.name = name
        self.type = type
        self.collection = collection
        self.eventType = eventType
        self.ruleTag = ruleTag
        self.params = params
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case collection
        case eventType = "event_type"
        case ruleTag = "rule_tag"
        case params
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encode(collection, forKey: .collection)
        try container.encode(eventType, forKey: .eventType)
        try container.encodeIfPresent(ruleTag, forKey: .ruleTag)
        try container.encodeIfPresent(params, forKey: .params)
    }
}

