//
// AnalyticsEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsEvent: Codable {

    /** Name of the analytics rule this event corresponds to */
    public var name: String
    /** Type of event (e.g., click, conversion, query, visit) */
    public var eventType: String
    public var data: AnalyticsEventData

    public init(name: String, eventType: String, data: AnalyticsEventData) {
        self.name = name
        self.eventType = eventType
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case eventType = "event_type"
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(data, forKey: .data)
    }
}
