//
// AnalyticsEventsRetrieveParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsEventsRetrieveParams: Codable {

    public var userId: String
    /** Analytics rule name */
    public var name: String
    /** Number of events to return (max 1000) */
    public var n: Int

    public init(userId: String, name: String, n: Int) {
        self.userId = userId
        self.name = name
        self.n = n
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case name
        case n
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(name, forKey: .name)
        try container.encode(n, forKey: .n)
    }
}
