//
// AnalyticsRuleParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AnalyticsRuleParameters: Codable {

    public var source: AnalyticsRuleParametersSource
    public var destination: AnalyticsRuleParametersDestination
    public var limit: Int?
    public var expandQuery: Bool?

    public init(source: AnalyticsRuleParametersSource, destination: AnalyticsRuleParametersDestination, limit: Int? = nil, expandQuery: Bool? = nil) {
        self.source = source
        self.destination = destination
        self.limit = limit
        self.expandQuery = expandQuery
    }

    public enum CodingKeys: String, CodingKey { 
        case source
        case destination
        case limit
        case expandQuery = "expand_query"
    }

}
