//
// AnalyticsEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsEvent: Codable {

    public var data: AnalyticsEventData
    /** Type of event (e.g., click, conversion, query, visit) */
    public var eventType: String
    /** Name of the analytics rule this event corresponds to */
    public var name: String

    public init(data: AnalyticsEventData, eventType: String, name: String) {
        self.data = data
        self.eventType = eventType
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case eventType = "event_type"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(name, forKey: .name)
    }
}
