//
// AnalyticsRuleSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AnalyticsRuleSchema: Codable {

    public var name: String
    public var type: String
    public var params: AnalyticsRuleParameters

    public init(name: String, type: String, params: AnalyticsRuleParameters) {
        self.name = name
        self.type = type
        self.params = params
    }


}
