//
// AnalyticsRuleParametersDestination.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AnalyticsRuleParametersDestination: Codable {

    public var collection: String?

    public init(collection: String? = nil) {
        self.collection = collection
    }


}
