//
// AnalyticsRuleUpsertSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AnalyticsRuleUpsertSchema: Codable {

    public enum ModelType: String, Codable { 
        case popularQueries = "popular_queries"
        case nohitsQueries = "nohits_queries"
        case counter = "counter"
    }
    public var type: ModelType
    public var params: AnalyticsRuleParameters

    public init(type: ModelType, params: AnalyticsRuleParameters) {
        self.type = type
        self.params = params
    }


}
