//
// AnalyticsRuleParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AnalyticsRuleParameters: Codable {

    public var source: AnalyticsRuleParametersSource
    public var destination: AnalyticsRuleParametersDestination
    public var limit: Int

    public init(source: AnalyticsRuleParametersSource, destination: AnalyticsRuleParametersDestination, limit: Int) {
        self.source = source
        self.destination = destination
        self.limit = limit
    }


}
