//
// AnalyticsRulesRetrieveSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AnalyticsRulesRetrieveSchema: Codable {

    public var rules: [AnalyticsRuleSchema]?

    public init(rules: [AnalyticsRuleSchema]? = nil) {
        self.rules = rules
    }


}
