//
// AnalyticsStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsStatus: Codable {

    public var docCounterEvents: Int?
    public var docLogEvents: Int?
    public var logPrefixQueries: Int?
    public var nohitsPrefixQueries: Int?
    public var popularPrefixQueries: Int?
    public var queryCounterEvents: Int?
    public var queryLogEvents: Int?

    public init(docCounterEvents: Int? = nil, docLogEvents: Int? = nil, logPrefixQueries: Int? = nil, nohitsPrefixQueries: Int? = nil, popularPrefixQueries: Int? = nil, queryCounterEvents: Int? = nil, queryLogEvents: Int? = nil) {
        self.docCounterEvents = docCounterEvents
        self.docLogEvents = docLogEvents
        self.logPrefixQueries = logPrefixQueries
        self.nohitsPrefixQueries = nohitsPrefixQueries
        self.popularPrefixQueries = popularPrefixQueries
        self.queryCounterEvents = queryCounterEvents
        self.queryLogEvents = queryLogEvents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docCounterEvents = "doc_counter_events"
        case docLogEvents = "doc_log_events"
        case logPrefixQueries = "log_prefix_queries"
        case nohitsPrefixQueries = "nohits_prefix_queries"
        case popularPrefixQueries = "popular_prefix_queries"
        case queryCounterEvents = "query_counter_events"
        case queryLogEvents = "query_log_events"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(docCounterEvents, forKey: .docCounterEvents)
        try container.encodeIfPresent(docLogEvents, forKey: .docLogEvents)
        try container.encodeIfPresent(logPrefixQueries, forKey: .logPrefixQueries)
        try container.encodeIfPresent(nohitsPrefixQueries, forKey: .nohitsPrefixQueries)
        try container.encodeIfPresent(popularPrefixQueries, forKey: .popularPrefixQueries)
        try container.encodeIfPresent(queryCounterEvents, forKey: .queryCounterEvents)
        try container.encodeIfPresent(queryLogEvents, forKey: .queryLogEvents)
    }
}

