//
// AnalyticsEventsRetrieveParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsEventsRetrieveParams: Codable {

    /** Number of events to return (max 1000) */
    public var n: Int
    /** Analytics rule name */
    public var name: String
    public var userId: String

    public init(n: Int, name: String, userId: String) {
        self.n = n
        self.name = name
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case n
        case name
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(n, forKey: .n)
        try container.encode(name, forKey: .name)
        try container.encode(userId, forKey: .userId)
    }
}
