//
// AnalyticsRuleCreateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyticsRuleCreateParams: Codable {

    public var captureSearchRequests: Bool?
    public var counterField: String?
    public var destinationCollection: String?
    public var expandQuery: Bool?
    public var limit: Int?
    public var metaFields: [String]?
    public var weight: Int?

    public init(captureSearchRequests: Bool? = nil, counterField: String? = nil, destinationCollection: String? = nil, expandQuery: Bool? = nil, limit: Int? = nil, metaFields: [String]? = nil, weight: Int? = nil) {
        self.captureSearchRequests = captureSearchRequests
        self.counterField = counterField
        self.destinationCollection = destinationCollection
        self.expandQuery = expandQuery
        self.limit = limit
        self.metaFields = metaFields
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case captureSearchRequests = "capture_search_requests"
        case counterField = "counter_field"
        case destinationCollection = "destination_collection"
        case expandQuery = "expand_query"
        case limit
        case metaFields = "meta_fields"
        case weight
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(captureSearchRequests, forKey: .captureSearchRequests)
        try container.encodeIfPresent(counterField, forKey: .counterField)
        try container.encodeIfPresent(destinationCollection, forKey: .destinationCollection)
        try container.encodeIfPresent(expandQuery, forKey: .expandQuery)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(metaFields, forKey: .metaFields)
        try container.encodeIfPresent(weight, forKey: .weight)
    }
}

