//
// AnalyticsRuleParametersSource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AnalyticsRuleParametersSource: Codable {

    public var collections: [String]?

    public init(collections: [String]? = nil) {
        self.collections = collections
    }


}
