//
// AnalyticsRuleUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Fields allowed to update on an analytics rule */
public struct AnalyticsRuleUpdate: Codable {

    public var name: String?
    public var params: AnalyticsRuleCreateParams?
    public var ruleTag: String?

    public init(name: String? = nil, params: AnalyticsRuleCreateParams? = nil, ruleTag: String? = nil) {
        self.name = name
        self.params = params
        self.ruleTag = ruleTag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case params
        case ruleTag = "rule_tag"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(params, forKey: .params)
        try container.encodeIfPresent(ruleTag, forKey: .ruleTag)
    }
}

