//
// ApiKeySchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiKeySchema: Codable {

    public var value: String?
    public var description: String
    public var actions: [String]
    public var collections: [String]
    public var expiresAt: Int64?

    public init(value: String? = nil, description: String, actions: [String], collections: [String], expiresAt: Int64? = nil) {
        self.value = value
        self.description = description
        self.actions = actions
        self.collections = collections
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case description
        case actions
        case collections
        case expiresAt = "expires_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encode(description, forKey: .description)
        try container.encode(actions, forKey: .actions)
        try container.encode(collections, forKey: .collections)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
    }
}

