//
// ApiKeySchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApiKeySchema: Codable {

    public var _description: String
    public var actions: [String]
    public var collections: [String]
    public var expiresAt: Int64

    public init(_description: String, actions: [String], collections: [String], expiresAt: Int64) {
        self._description = _description
        self.actions = actions
        self.collections = collections
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case actions
        case collections
        case expiresAt = "expires_at"
    }

}
