//
// CollectionAliasesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CollectionAliasesResponse: Codable {

    public var aliases: [CollectionAlias]

    public init(aliases: [CollectionAlias]) {
        self.aliases = aliases
    }


}
