//
// CollectionAlias.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CollectionAlias: Codable {

    /** Name of the collection the alias mapped to */
    public var collectionName: String
    /** Name of the collection alias */
    public var name: String

    public init(collectionName: String, name: String) {
        self.collectionName = collectionName
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collectionName = "collection_name"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(collectionName, forKey: .collectionName)
        try container.encode(name, forKey: .name)
    }
}
