//
// CollectionAliasSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CollectionAliasSchema: Codable {

    /** Name of the collection you wish to map the alias to */
    public var collectionName: String

    public init(collectionName: String) {
        self.collectionName = collectionName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collectionName = "collection_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(collectionName, forKey: .collectionName)
    }
}
