//
// CollectionAliasSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CollectionAliasSchema: Codable {

    /** Name of the collection you wish to map the alias to */
    public var collectionName: String

    public init(collectionName: String) {
        self.collectionName = collectionName
    }

    public enum CodingKeys: String, CodingKey { 
        case collectionName = "collection_name"
    }

}
