//
// CollectionUpdateSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CollectionUpdateSchema: Codable {

    /** A list of fields for querying, filtering and faceting */
    public var fields: [Field]
    /** List of synonym set names to associate with this collection */
    public var synonymSets: [String]?
    /** Optional details about the collection, e.g., when it was created, who created it etc.  */
    public var metadata: AnyCodable?

    public init(fields: [Field], synonymSets: [String]? = nil, metadata: AnyCodable? = nil) {
        self.fields = fields
        self.synonymSets = synonymSets
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fields
        case synonymSets = "synonym_sets"
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fields, forKey: .fields)
        try container.encodeIfPresent(synonymSets, forKey: .synonymSets)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}
