//
// CollectionUpdateSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CollectionUpdateSchema: Codable {

    /** A list of fields for querying, filtering and faceting */
    public var fields: [Field]

    public init(fields: [Field]) {
        self.fields = fields
    }


}
