//
// CreateAnalyticsRule200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CreateAnalyticsRule200Response: Codable, JSONEncodable {
    case typeAnalyticsRule(AnalyticsRule)
    case type[CreateAnalyticsRule200ResponseOneOfInner]([CreateAnalyticsRule200ResponseOneOfInner])

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAnalyticsRule(let value):
            try container.encode(value)
        case .type[CreateAnalyticsRule200ResponseOneOfInner](let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AnalyticsRule.self) {
            self = .typeAnalyticsRule(value)
        } else if let value = try? container.decode([CreateAnalyticsRule200ResponseOneOfInner].self) {
            self = .type[CreateAnalyticsRule200ResponseOneOfInner](value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of CreateAnalyticsRule200Response"))
        }
    }
}

