//
// CreateAnalyticsRuleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CreateAnalyticsRuleRequest: Codable, JSONEncodable {
    case typeAnalyticsRuleCreate(AnalyticsRuleCreate)
    case type[AnalyticsRuleCreate]([AnalyticsRuleCreate])

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAnalyticsRuleCreate(let value):
            try container.encode(value)
        case .type[AnalyticsRuleCreate](let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AnalyticsRuleCreate.self) {
            self = .typeAnalyticsRuleCreate(value)
        } else if let value = try? container.decode([AnalyticsRuleCreate].self) {
            self = .type[AnalyticsRuleCreate](value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of CreateAnalyticsRuleRequest"))
        }
    }
}

