//
// CurationSetCreateSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CurationSetCreateSchema: Codable {

    /** Optional description for the curation set */
    public var description: String?
    /** Array of curation items */
    public var items: [CurationItemCreateSchema]

    public init(items: [CurationItemCreateSchema], description: String? = nil) {
        self.description = description
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(items, forKey: .items)
    }
}
