//
// CurationInclude.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CurationInclude: Codable {

    /** document id that should be included */
    public var id: String
    /** position number where document should be included in the search results */
    public var position: Int

    public init(id: String, position: Int) {
        self.id = id
        self.position = position
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case position
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(position, forKey: .position)
    }
}
