//
// CurationSetSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CurationSetSchema: Codable {

    /** Array of curation items */
    public var items: [CurationItemCreateSchema]
    /** Optional description for the curation set */
    public var description: String?
    public var name: String

    public init(items: [CurationItemCreateSchema], description: String? = nil, name: String) {
        self.items = items
        self.description = description
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case description
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(name, forKey: .name)
    }
}

