//
// DeleteDocumentsParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteDocumentsParameters: Codable {

    /** Batch size parameter controls the number of documents that should be deleted at a time. A larger value will speed up deletions, but will impact performance of other operations running on the server. */
    public var batchSize: Int?
    public var filterBy: String
    public var ignoreNotFound: Bool?
    /** When true, removes all documents from the collection while preserving the collection and its schema. */
    public var truncate: Bool?

    public init(filterBy: String, batchSize: Int? = nil, ignoreNotFound: Bool? = nil, truncate: Bool? = nil) {
        self.batchSize = batchSize
        self.filterBy = filterBy
        self.ignoreNotFound = ignoreNotFound
        self.truncate = truncate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case batchSize = "batch_size"
        case filterBy = "filter_by"
        case ignoreNotFound = "ignore_not_found"
        case truncate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(batchSize, forKey: .batchSize)
        try container.encode(filterBy, forKey: .filterBy)
        try container.encodeIfPresent(ignoreNotFound, forKey: .ignoreNotFound)
        try container.encodeIfPresent(truncate, forKey: .truncate)
    }
}
