//
// DeleteDocumentsParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeleteDocumentsParameters: Codable {

    public var filterBy: String?
    /** Batch size parameter controls the number of documents that should be deleted at a time. A larger value will speed up deletions, but will impact performance of other operations running on the server. */
    public var batchSize: Int?

    public init(filterBy: String? = nil, batchSize: Int? = nil) {
        self.filterBy = filterBy
        self.batchSize = batchSize
    }

    public enum CodingKeys: String, CodingKey { 
        case filterBy = "filter_by"
        case batchSize = "batch_size"
    }

}
