//
// DirtyValues.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DirtyValues: String, Codable, CaseIterable {
    case coerceOrReject = "coerce_or_reject"
    case coerceOrDrop = "coerce_or_drop"
    case drop = "drop"
    case reject = "reject"
}
