//
// DropTokensMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Dictates the direction in which the words in the query must be dropped when the original words in the query do not appear in any document. Values: right_to_left (default), left_to_right, both_sides:3 A note on both_sides:3 - for queries up to 3 tokens (words) in length, this mode will drop tokens from both sides and exhaustively rank all matching results. If query length is greater than 3 words, Typesense will just fallback to default behavior of right_to_left  */
public enum DropTokensMode: String, Codable, CaseIterable {
    case rightToLeft = "right_to_left"
    case leftToRight = "left_to_right"
    case bothSides3 = "both_sides:3"
}
