//
// FacetCountsCountsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FacetCountsCountsInner: Codable {

    public var count: Int?
    public var highlighted: String?
    public var parent: AnyCodable?
    public var value: String?

    public init(count: Int? = nil, highlighted: String? = nil, parent: AnyCodable? = nil, value: String? = nil) {
        self.count = count
        self.highlighted = highlighted
        self.parent = parent
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case highlighted
        case parent
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(highlighted, forKey: .highlighted)
        try container.encodeIfPresent(parent, forKey: .parent)
        try container.encodeIfPresent(value, forKey: .value)
    }
}
