//
// FacetCountsStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FacetCountsStats: Codable {

    public var max: Double?
    public var min: Double?
    public var sum: Double?
    public var totalValues: Int?
    public var avg: Double?

    public init(max: Double? = nil, min: Double? = nil, sum: Double? = nil, totalValues: Int? = nil, avg: Double? = nil) {
        self.max = max
        self.min = min
        self.sum = sum
        self.totalValues = totalValues
        self.avg = avg
    }

    public enum CodingKeys: String, CodingKey { 
        case max
        case min
        case sum
        case totalValues = "total_values"
        case avg
    }

}
