//
// FacetCounts.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FacetCounts: Codable {

    public var counts: [FacetCountsCounts]?
    public var fieldName: String?
    public var stats: FacetCountsStats?

    public init(counts: [FacetCountsCounts]? = nil, fieldName: String? = nil, stats: FacetCountsStats? = nil) {
        self.counts = counts
        self.fieldName = fieldName
        self.stats = stats
    }

    public enum CodingKeys: String, CodingKey { 
        case counts
        case fieldName = "field_name"
        case stats
    }

}
