//
// FacetCounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FacetCounts: Codable {

    public var counts: [FacetCountsCountsInner]?
    public var fieldName: String?
    public var stats: FacetCountsStats?

    public init(counts: [FacetCountsCountsInner]? = nil, fieldName: String? = nil, stats: FacetCountsStats? = nil) {
        self.counts = counts
        self.fieldName = fieldName
        self.stats = stats
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case counts
        case fieldName = "field_name"
        case stats
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(counts, forKey: .counts)
        try container.encodeIfPresent(fieldName, forKey: .fieldName)
        try container.encodeIfPresent(stats, forKey: .stats)
    }
}
