//
// FacetCountsCounts.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FacetCountsCounts: Codable {

    public var count: Int?
    public var highlighted: String?
    public var value: String?

    public init(count: Int? = nil, highlighted: String? = nil, value: String? = nil) {
        self.count = count
        self.highlighted = highlighted
        self.value = value
    }


}
