//
// FacetCountsStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FacetCountsStats: Codable {

    public var max: Double?
    public var min: Double?
    public var sum: Double?
    public var totalValues: Int?
    public var avg: Double?

    public init(max: Double? = nil, min: Double? = nil, sum: Double? = nil, totalValues: Int? = nil, avg: Double? = nil) {
        self.max = max
        self.min = min
        self.sum = sum
        self.totalValues = totalValues
        self.avg = avg
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case max
        case min
        case sum
        case totalValues = "total_values"
        case avg
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(max, forKey: .max)
        try container.encodeIfPresent(min, forKey: .min)
        try container.encodeIfPresent(sum, forKey: .sum)
        try container.encodeIfPresent(totalValues, forKey: .totalValues)
        try container.encodeIfPresent(avg, forKey: .avg)
    }
}

