//
// FieldEmbedModelConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FieldEmbedModelConfig: Codable {

    public var modelName: String
    public var apiKey: String?
    public var accessToken: String?
    public var clientId: String?
    public var clientSecret: String?
    public var projectId: String?

    public init(modelName: String, apiKey: String? = nil, accessToken: String? = nil, clientId: String? = nil, clientSecret: String? = nil, projectId: String? = nil) {
        self.modelName = modelName
        self.apiKey = apiKey
        self.accessToken = accessToken
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey { 
        case modelName = "model_name"
        case apiKey = "api_key"
        case accessToken = "access_token"
        case clientId = "client_id"
        case clientSecret = "client_secret"
        case projectId = "project_id"
    }

}
