//
// FieldEmbed.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FieldEmbed: Codable {

    public var from: [String]
    public var modelConfig: FieldEmbedModelConfig

    public init(from: [String], modelConfig: FieldEmbedModelConfig) {
        self.from = from
        self.modelConfig = modelConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case modelConfig = "model_config"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(from, forKey: .from)
        try container.encode(modelConfig, forKey: .modelConfig)
    }
}
