//
// Field.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Field: Codable {

    public enum ModelType: String, Codable { 
        case string = "string"
        case int32 = "int32"
        case int64 = "int64"
        case float = "float"
        case bool = "bool"
        case stringarr = "string[]"
        case int32arr = "int32[]"
        case int64arr = "int64[]"
        case floatarr = "float[]"
        case boolarr = "bool[]"
    }
    public var name: String
    public var type: ModelType
    public var _optional: Bool
    public var facet: Bool
    public var index: Bool?

    public init(name: String, type: ModelType, _optional: Bool, facet: Bool, index: Bool? = nil) {
        self.name = name
        self.type = type
        self._optional = _optional
        self.facet = facet
        self.index = index
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case type
        case _optional = "optional"
        case facet
        case index
    }

}
