//
// Field.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Field: Codable {

    public var name: String
    public var type: String
    public var _optional: Bool?
    public var facet: Bool?
    public var index: Bool?
    public var inFix: Bool?
    public var sort: Bool?
    public var locale: String?


    public init(name: String, type: String, _optional: Bool? = nil, facet: Bool? = nil, index: Bool? = nil, inFix: Bool? = nil, sort: Bool? = nil, locale: String? = nil) {
        self.name = name
        self.type = type
        self._optional = _optional
        self.facet = facet
        self.index = index
        self.inFix = inFix
        self.sort = sort
        self.locale = locale
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case type
        case _optional = "optional"
        case facet
        case index
        case inFix = "infix"
        case sort
        case locale
    }

}
