//
// FieldEmbed.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FieldEmbed: Codable {

    public var from: [String]
    public var modelConfig: FieldEmbedModelConfig

    public init(from: [String], modelConfig: FieldEmbedModelConfig) {
        self.from = from
        self.modelConfig = modelConfig
    }

    public enum CodingKeys: String, CodingKey { 
        case from
        case modelConfig = "model_config"
    }

}
