//
// GetCollectionsParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCollectionsParameters: Codable {

    /** Comma-separated list of fields from the collection to exclude from the response */
    public var excludeFields: String?
    /** Number of collections to fetch. Default: returns all collections.  */
    public var limit: Int?
    /** Identifies the starting point to return collections when paginating. */
    public var offset: Int?

    public init(excludeFields: String? = nil, limit: Int? = nil, offset: Int? = nil) {
        self.excludeFields = excludeFields
        self.limit = limit
        self.offset = offset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case excludeFields = "exclude_fields"
        case limit
        case offset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(excludeFields, forKey: .excludeFields)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(offset, forKey: .offset)
    }
}

