//
// ImportDocumentsParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImportDocumentsParameters: Codable {

    public var action: IndexAction?
    public var batchSize: Int?
    public var dirtyValues: DirtyValues?
    public var remoteEmbeddingBatchSize: Int?
    public var returnDoc: Bool?
    public var returnId: Bool?

    public init(action: IndexAction? = nil, batchSize: Int? = nil, dirtyValues: DirtyValues? = nil, remoteEmbeddingBatchSize: Int? = nil, returnDoc: Bool? = nil, returnId: Bool? = nil) {
        self.action = action
        self.batchSize = batchSize
        self.dirtyValues = dirtyValues
        self.remoteEmbeddingBatchSize = remoteEmbeddingBatchSize
        self.returnDoc = returnDoc
        self.returnId = returnId
    }

    public enum CodingKeys: String, CodingKey {
        case action
        case batchSize = "batch_size"
        case dirtyValues = "dirty_values"
        case remoteEmbeddingBatchSize = "remote_embedding_batch_size"
        case returnDoc = "return_doc"
        case returnId = "return_id"
    }

}
