//
// IndexAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum IndexAction: String, Codable, CaseIterable {
    case create = "create"
    case update = "update"
    case upsert = "upsert"
    case emplace = "emplace"
}
