//
// InlineResponse2001.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2001: Codable {

    /** The number of documents that have been updated */
    public var numUpdated: Int

    public init(numUpdated: Int) {
        self.numUpdated = numUpdated
    }

    public enum CodingKeys: String, CodingKey { 
        case numUpdated = "num_updated"
    }

}
