//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var numDeleted: Int

    public init(numDeleted: Int) {
        self.numDeleted = numDeleted
    }

    public enum CodingKeys: String, CodingKey { 
        case numDeleted = "num_deleted"
    }

}
