//
// InlineResponse2002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2002: Codable {

    public var version: String?

    public init(version: String? = nil) {
        self.version = version
    }


}
