//
// MultiSearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MultiSearchResult: Codable {

    public var conversation: SearchResultConversation?
    public var results: [MultiSearchResultItem]

    public init(conversation: SearchResultConversation? = nil, results: [MultiSearchResultItem]) {
        self.conversation = conversation
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case conversation
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(conversation, forKey: .conversation)
        try container.encode(results, forKey: .results)
    }
}

