//
// MultiSearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MultiSearchResult<T: Codable>: Codable {

    public var results: [MultiSearchResultItem<T>]
    public var conversation: SearchResultConversation?

    public init(results: [MultiSearchResultItem<T>], conversation: SearchResultConversation? = nil) {
        self.results = results
        self.conversation = conversation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
        case conversation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(results, forKey: .results)
        try container.encodeIfPresent(conversation, forKey: .conversation)
    }
}
