//
// MultiSearchSearchesParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MultiSearchSearchesParameter: Codable {

    public var searches: [MultiSearchCollectionParameters]
    /** When true, merges the search results from each search query into a single ordered set of hits. */
    public var union: Bool? = false

    public init(searches: [MultiSearchCollectionParameters], union: Bool? = false) {
        self.searches = searches
        self.union = union
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case searches
        case union
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(searches, forKey: .searches)
        try container.encodeIfPresent(union, forKey: .union)
    }
}
