//
// MultiSearchSearchesParameter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiSearchSearchesParameter: Codable {

    public var searches: [MultiSearchCollectionParameters]

    public init(searches: [MultiSearchCollectionParameters]) {
        self.searches = searches
    }


}
