//
// MultiSearchResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiSearchResult<T: Decodable>: Decodable {

    public var results: [SearchResult<T>]
    public var conversation: SearchResultConversation?

    public init(results: [SearchResult<T>], conversation: SearchResultConversation? = nil) {
        self.results = results
        self.conversation = conversation
    }


}
