//
// MultiSearchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiSearchResponse: Codable {

    public var results: [SearchResult]?

    public init(results: [SearchResult]? = nil) {
        self.results = results
    }


}
