//
// PresetSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PresetSchema: Codable {

    public var value: PresetUpsertSchemaValue
    public var name: String

    public init(value: PresetUpsertSchemaValue, name: String) {
        self.value = value
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(name, forKey: .name)
    }
}
