//
// PresetUpsertSchemaValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PresetUpsertSchemaValue: Codable, JSONEncodable {
    case typeMultiSearchSearchesParameter(MultiSearchSearchesParameter)
    case typeSearchParameters(SearchParameters)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeMultiSearchSearchesParameter(let value):
            try container.encode(value)
        case .typeSearchParameters(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(MultiSearchSearchesParameter.self) {
            self = .typeMultiSearchSearchesParameter(value)
        } else if let value = try? container.decode(SearchParameters.self) {
            self = .typeSearchParameters(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PresetUpsertSchemaValue"))
        }
    }
}

