//
// SchemaChangeStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SchemaChangeStatus: Codable {

    /** Number of documents that have been altered */
    public var alteredDocs: Int?
    /** Name of the collection being modified */
    public var collection: String?
    /** Number of documents that have been validated */
    public var validatedDocs: Int?

    public init(alteredDocs: Int? = nil, collection: String? = nil, validatedDocs: Int? = nil) {
        self.alteredDocs = alteredDocs
        self.collection = collection
        self.validatedDocs = validatedDocs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alteredDocs = "altered_docs"
        case collection
        case validatedDocs = "validated_docs"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(alteredDocs, forKey: .alteredDocs)
        try container.encodeIfPresent(collection, forKey: .collection)
        try container.encodeIfPresent(validatedDocs, forKey: .validatedDocs)
    }
}

