//
// SearchOverrideSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchOverrideSchema: Codable {

    public var rule: SearchOverrideRule
    /** List of document &#x60;id&#x60;s that should be included in the search results with their corresponding &#x60;position&#x60;s. */
    public var includes: [SearchOverrideInclude]
    /** List of document &#x60;id&#x60;s that should be excluded from the search results. */
    public var excludes: [SearchOverrideExclude]

    public init(rule: SearchOverrideRule, includes: [SearchOverrideInclude], excludes: [SearchOverrideExclude]) {
        self.rule = rule
        self.includes = includes
        self.excludes = excludes
    }


}
