//
// SearchResultConversation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchResultConversation: Codable {

    public var answer: String
    public var conversationHistory: [AnyCodable]
    public var conversationId: String
    public var query: String

    public init(answer: String, conversationHistory: [AnyCodable], conversationId: String, query: String) {
        self.answer = answer
        self.conversationHistory = conversationHistory
        self.conversationId = conversationId
        self.query = query
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case answer
        case conversationHistory = "conversation_history"
        case conversationId = "conversation_id"
        case query
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(answer, forKey: .answer)
        try container.encode(conversationHistory, forKey: .conversationHistory)
        try container.encode(conversationId, forKey: .conversationId)
        try container.encode(query, forKey: .query)
    }
}
