//
// SearchHighlight.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchHighlight: Codable {

    public var field: String
    /** Present only for (non-array) string fields */
    public var snippet: String
    /** Present only for (array) string[] fields */
    public var snippets: [String]
    /** The indices property will be present only for string[] fields and will contain the corresponding indices of the snippets in the search field */
    public var indices: [Int]
    public var matchedTokens: [String]

    public init(field: String, snippet: String, snippets: [String], indices: [Int], matchedTokens: [String]) {
        self.field = field
        self.snippet = snippet
        self.snippets = snippets
        self.indices = indices
        self.matchedTokens = matchedTokens
    }

    public enum CodingKeys: String, CodingKey { 
        case field
        case snippet
        case snippets
        case indices
        case matchedTokens = "matched_tokens"
    }

}
