//
// SearchOverrideInclude.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchOverrideInclude: Codable {

    /** document id that should be included */
    public var _id: String
    /** position number where document should be included in the search results */
    public var position: Int

    public init(_id: String, position: Int) {
        self._id = _id
        self.position = position
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case position
    }

}
