//
// SearchResultRequestParamsVoiceQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchResultRequestParamsVoiceQuery: Codable {

    public var transcribedQuery: String?

    public init(transcribedQuery: String? = nil) {
        self.transcribedQuery = transcribedQuery
    }

    public enum CodingKeys: String, CodingKey { 
        case transcribedQuery = "transcribed_query"
    }

}
