//
// SearchGroupedHit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchGroupedHit: Codable {

    public var groupKey: [String]
    /** The documents that matched the search query */
    public var hits: [SearchResultHit]

    public init(groupKey: [String], hits: [SearchResultHit]) {
        self.groupKey = groupKey
        self.hits = hits
    }

    public enum CodingKeys: String, CodingKey { 
        case groupKey = "group_key"
        case hits
    }

}
