//
// SearchOverridesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchOverridesResponse: Codable {

    public var overrides: [SearchOverride]

    public init(overrides: [SearchOverride]) {
        self.overrides = overrides
    }


}
