//
// SearchOverride.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchOverride: Codable {

    public var rule: SearchOverrideRule
    /** List of document &#x60;id&#x60;s that should be included in the search results with their corresponding &#x60;position&#x60;s. */
    public var includes: [SearchOverrideInclude]
    /** List of document &#x60;id&#x60;s that should be excluded from the search results. */
    public var excludes: [SearchOverrideExclude]
    /** A filter by clause that is applied to any search query that matches the override rule.  */
    public var filterBy: String?
    /** Indicates whether search query tokens that exist in the override&#x27;s rule should be removed from the search query.  */
    public var removeMatchedTokens: Bool?
    public var _id: String

    public init(rule: SearchOverrideRule, includes: [SearchOverrideInclude], excludes: [SearchOverrideExclude], filterBy: String? = nil, removeMatchedTokens: Bool? = nil, _id: String) {
        self.rule = rule
        self.includes = includes
        self.excludes = excludes
        self.filterBy = filterBy
        self.removeMatchedTokens = removeMatchedTokens
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case rule
        case includes
        case excludes
        case filterBy = "filter_by"
        case removeMatchedTokens = "remove_matched_tokens"
        case _id = "id"
    }

}
