//
// SearchSynonymsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchSynonymsResponse: Codable {

    public var synonyms: [SearchSynonym]

    public init(synonyms: [SearchSynonym]) {
        self.synonyms = synonyms
    }


}
