//
// SearchRequestParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchRequestParams: Codable {

    public var collectionName: String
    public var q: String
    public var perPage: Int
    public var voiceQuery: SearchRequestParamsVoiceQuery?

    public init(collectionName: String, q: String, perPage: Int, voiceQuery: SearchRequestParamsVoiceQuery? = nil) {
        self.collectionName = collectionName
        self.q = q
        self.perPage = perPage
        self.voiceQuery = voiceQuery
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collectionName = "collection_name"
        case q
        case perPage = "per_page"
        case voiceQuery = "voice_query"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(collectionName, forKey: .collectionName)
        try container.encode(q, forKey: .q)
        try container.encode(perPage, forKey: .perPage)
        try container.encodeIfPresent(voiceQuery, forKey: .voiceQuery)
    }
}
