//
// SearchSynonymsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchSynonymsResponse: Codable {

    public var synonyms: [SearchSynonym]

    public init(synonyms: [SearchSynonym]) {
        self.synonyms = synonyms
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case synonyms
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(synonyms, forKey: .synonyms)
    }
}
