//
// SearchResultHitHybridSearchInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Information about hybrid search scoring */
public struct SearchResultHitHybridSearchInfo: Codable {

    /** Combined score from rank fusion of text and vector search */
    public var rankFusionScore: Float?

    public init(rankFusionScore: Float? = nil) {
        self.rankFusionScore = rankFusionScore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rankFusionScore = "rank_fusion_score"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rankFusionScore, forKey: .rankFusionScore)
    }
}

