//
// SearchOverridesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchOverridesResponse<T: Codable>: Codable {

    public var overrides: [SearchOverride<T>]

    public init(overrides: [SearchOverride<T>]) {
        self.overrides = overrides
    }


}
