//
// SnapshotParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SnapshotParameters: Codable {

    public var snapshotPath: String?

    public init(snapshotPath: String? = nil) {
        self.snapshotPath = snapshotPath
    }

    public enum CodingKeys: String, CodingKey { 
        case snapshotPath = "snapshot_path"
    }

}
