//
// StemmingDictionaryWordsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StemmingDictionaryWordsInner: Codable {

    /** The word form to be stemmed */
    public var word: String
    /** The root form of the word */
    public var root: String

    public init(word: String, root: String) {
        self.word = word
        self.root = root
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case word
        case root
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(word, forKey: .word)
        try container.encode(root, forKey: .root)
    }
}
