//
// StopwordsSetRetrieveSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StopwordsSetRetrieveSchema: Codable {

    public var stopwords: StopwordsSetSchema

    public init(stopwords: StopwordsSetSchema) {
        self.stopwords = stopwords
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stopwords
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(stopwords, forKey: .stopwords)
    }
}

