//
// StopwordsSetRetrieveSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StopwordsSetRetrieveSchema: Codable {

    public var stopwords: StopwordsSetSchema

    public init(stopwords: StopwordsSetSchema) {
        self.stopwords = stopwords
    }


}
