//
// StopwordsSetSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StopwordsSetSchema: Codable {

    public var _id: String
    public var stopwords: [String]
    public var locale: String?

    public init(_id: String, stopwords: [String], locale: String? = nil) {
        self._id = _id
        self.stopwords = stopwords
        self.locale = locale
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case stopwords
        case locale
    }

}
