//
// StopwordsSetUpsertSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StopwordsSetUpsertSchema: Codable {

    public var locale: String?
    public var stopwords: [String]

    public init(stopwords: [String], locale: String? = nil) {
        self.locale = locale
        self.stopwords = stopwords
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locale
        case stopwords
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encode(stopwords, forKey: .stopwords)
    }
}
