//
// StopwordsSetUpsertSchema.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StopwordsSetUpsertSchema: Codable {

    public var stopwords: [String]
    public var locale: String?

    public init(stopwords: [String], locale: String? = nil) {
        self.stopwords = stopwords
        self.locale = locale
    }


}
