//
// SynonymSetSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SynonymSetSchema: Codable {

    /** Array of synonym items */
    public var items: [SynonymItemSchema]
    /** Name of the synonym set */
    public var name: String

    public init(items: [SynonymItemSchema], name: String) {
        self.items = items
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(name, forKey: .name)
    }
}
