//
// SynonymItemSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SynonymItemSchema: Codable {

    /** Array of words that should be considered as synonyms */
    public var synonyms: [String]
    /** For 1-way synonyms, indicates the root word that words in the synonyms parameter map to */
    public var root: String?
    /** Locale for the synonym, leave blank to use the standard tokenizer */
    public var locale: String?
    /** By default, special characters are dropped from synonyms. Use this attribute to specify which special characters should be indexed as is */
    public var symbolsToIndex: [String]?
    /** Unique identifier for the synonym item */
    public var id: String

    public init(synonyms: [String], id: String, root: String? = nil, locale: String? = nil, symbolsToIndex: [String]? = nil) {
        self.synonyms = synonyms
        self.root = root
        self.locale = locale
        self.symbolsToIndex = symbolsToIndex
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case synonyms
        case root
        case locale
        case symbolsToIndex = "symbols_to_index"
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(synonyms, forKey: .synonyms)
        try container.encodeIfPresent(root, forKey: .root)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(symbolsToIndex, forKey: .symbolsToIndex)
        try container.encode(id, forKey: .id)
    }
}
