//
// SynonymSetsRetrieveSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SynonymSetsRetrieveSchema: Codable {

    /** Array of synonym sets */
    public var synonymSets: [SynonymSetSchema]

    public init(synonymSets: [SynonymSetSchema]) {
        self.synonymSets = synonymSets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case synonymSets = "synonym_sets"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(synonymSets, forKey: .synonymSets)
    }
}
