//
// ToggleSlowRequestLogRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ToggleSlowRequestLogRequest: Codable {

    public var logSlowRequestsTimeMs: Int

    public init(logSlowRequestsTimeMs: Int) {
        self.logSlowRequestsTimeMs = logSlowRequestsTimeMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case logSlowRequestsTimeMs = "log-slow-requests-time-ms"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(logSlowRequestsTimeMs, forKey: .logSlowRequestsTimeMs)
    }
}

