//
// UpdateDocumentsParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateDocumentsByFilterParameters: Codable {

    public var filterBy: String?

    public init(filterBy: String? = nil) {
        self.filterBy = filterBy
    }

    public enum CodingKeys: String, CodingKey {
        case filterBy = "filter_by"
    }

}
