//
// UpdateDocuments200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateDocuments200Response: Codable {

    /** The number of documents that have been updated */
    public var numUpdated: Int

    public init(numUpdated: Int) {
        self.numUpdated = numUpdated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case numUpdated = "num_updated"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(numUpdated, forKey: .numUpdated)
    }
}

