//
// UpdateDocumentsParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateDocumentsParameters: Codable {

    public var filterBy: String?

    public init(filterBy: String? = nil) {
        self.filterBy = filterBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filterBy = "filter_by"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filterBy, forKey: .filterBy)
    }
}
