//
// VoiceQueryModelCollectionConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Configuration for the voice query model  */
public struct VoiceQueryModelCollectionConfig: Codable {

    public var modelName: String?

    public init(modelName: String? = nil) {
        self.modelName = modelName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case modelName = "model_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(modelName, forKey: .modelName)
    }
}

