//
// VoiceQueryModelCollectionConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Configuration for the voice query model  */

public struct VoiceQueryModelCollectionConfig: Codable {

    public var modelName: String?

    public init(modelName: String? = nil) {
        self.modelName = modelName
    }

    public enum CodingKeys: String, CodingKey { 
        case modelName = "model_name"
    }

}
