//
// ExportDocumentsParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExportDocumentsParameters: Codable {

    /** Filter conditions for refining your search results. Separate multiple conditions with &amp;&amp;. */
    public var filterBy: String?
    /** List of fields from the document to include in the search result */
    public var includeFields: [String]?
    /** List of fields from the document to exclude in the search result */
    public var excludeFields: [String]?

    public init(filterBy: String? = nil, includeFields: [String]? = nil, excludeFields: [String]? = nil) {
        self.filterBy = filterBy
        self.includeFields = includeFields
        self.excludeFields = excludeFields
    }

    public enum CodingKeys: String, CodingKey { 
        case filterBy = "filter_by"
        case includeFields = "include_fields"
        case excludeFields = "exclude_fields"
    }

}
