//
// HealthStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HealthStatus: Codable {

    public var ok: Bool

    public init(ok: Bool) {
        self.ok = ok
    }


}
