//
// ScopedKeyParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ScopedKeyParameters: Codable {

    public var filterBy: String?
    public var expiresAt: Decimal?

    public init(filterBy: String? = nil, expiresAt: Decimal? = nil) {
        self.filterBy = filterBy
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey { 
        case filterBy = "filter_by"
        case expiresAt = "expires_at"
    }

}
