//
// SearchSynonym.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchSynonym: Codable {

    /** For 1-way synonyms, indicates the root word that words in the &#x60;synonyms&#x60; parameter map to. */
    public var root: String
    /** Array of words that should be considered as synonyms. */
    public var synonyms: [String]
    public var _id: String

    public init(root: String, synonyms: [String], _id: String) {
        self.root = root
        self.synonyms = synonyms
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case root
        case synonyms
        case _id = "id"
    }

}
