//
// SearchResultHit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchResultHit: Codable {

    /** Contains highlighted portions of the search fields */
    public var highlights: [SearchHighlight]
    /** Can be any key-value pair */
    public var document: String

    public init(highlights: [SearchHighlight], document: String) {
        self.highlights = highlights
        self.document = document
    }


}
